# Generated by Django 4.2.6 on 2023-10-31 16:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='turmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='grupimg/%Y/%m/%d')),
                ('data_incricao', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(max_length=600)),
                ('email', models.CharField(max_length=200)),
                ('nome_aplicativo', models.CharField(max_length=180)),
                ('link_aplicativo', models.CharField(max_length=180)),
                ('arquivo_aplicativo', models.TextField(max_length=600)),
                ('nome_equipe', models.CharField(max_length=180)),
                ('tutor', models.CharField(max_length=180)),
                ('lider_equipe', models.CharField(max_length=180)),
                ('integrantes', models.TextField()),
                ('votos', models.PositiveIntegerField(default=0)),
                ('escolaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sysdevotacao.escola')),
            ],
        ),
    ]
