# Generated by Django 4.2.6 on 2023-11-07 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sysdevotacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='grupimg/%Y/%m/%d')),
            ],
        ),
        migrations.RemoveField(
            model_name='turmas',
            name='imagem',
        ),
        migrations.AddField(
            model_name='turmas',
            name='imagens',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sysdevotacao.imagem'),
            preserve_default=False,
        ),
    ]
