# Generated by Django 4.2.5 on 2023-11-09 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sysdevotacao', '0002_imagem_remove_turmas_imagem_turmas_imagens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turmas',
            name='imagens',
        ),
        migrations.DeleteModel(
            name='imagem',
        ),
    ]
