# Generated by Django 4.2.5 on 2023-11-09 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sysdevotacao', '0003_remove_turmas_imagens_delete_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turmas',
            old_name='link_aplicativo',
            new_name='linkYoutube',
        ),
    ]
