# Generated by Django 4.2.6 on 2023-11-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysdevotacao', '0005_rename_lider_equipe_turmas_nomeaplicativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turmas',
            name='votos',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
